config/routes.rb
Rails.application.routes.draw do
root to: 'cities#index'

  resources :cities do
    resources :forecasts
  end
  resources :states

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :forecasts
  belongs_to :state
end

app/models/forecast.rb
class Forecast < ApplicationRecord
  belongs_to :city
end

app/models/state.rb
class State < ApplicationRecord
  has_many :cities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]
  

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.order('name')
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  def city_forecasts_path
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)
  
    respond_to do |format|
      if @city.save
        format.html { redirect_to city_path(@city), notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to city_path(@city), notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_path, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :state_id)
    end
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  before_action :set_forecast, only: [:show, :edit, :update, :destroy]
  before_action :set_city
  

  # GET /forecasts
  # GET /forecasts.json
  def index
    @forecasts = Forecast.order('date').select {|forecast| forecast.city_id == @city.id}
  end

  # GET /forecasts/1
  # GET /forecasts/1.json
  def show
  end

  # GET /forecasts/new
  def new
    @forecast = Forecast.new
  end

  # GET /forecasts/1/edit
  def edit
  end

  # POST /forecasts
  # POST /forecasts.json
  def create
    @forecast = Forecast.new(forecast_params)
    @forecast.city_id = @city.id

    respond_to do |format|
      if @forecast.save
        format.html { redirect_to city_forecast_path(@forecast, @city), notice: 'Forecast was successfully created.' }
        format.json { render :show, status: :created, location: @forecast }
      else
        format.html { render :new }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forecasts/1
  # PATCH/PUT /forecasts/1.json
  def update
    respond_to do |format|
      if @forecast.update(forecast_params)
        format.html { redirect_to city_forecast_path(@forecast, @city), notice: 'Forecast was successfully updated.' }
        format.json { render :show, status: :ok, location: @forecast }
      else
        format.html { render :edit }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forecasts/1
  # DELETE /forecasts/1.json
  def destroy
    @forecast.destroy
    respond_to do |format|
      format.html { redirect_to city_forecasts_path(@city), notice: 'Forecast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forecast
      @forecast = Forecast.find(params[:id])
    end

    def set_city
      @city = City.find(params[:city_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forecast_params
      params.require(:forecast).permit(:min_temp, :max_temp, :short_description, :chance_of_rain, :long_description, :uv_index, :date, :possible_rainfall, :image_url, :city_id)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.order('name')
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @cities = City.where( "state_id = ?", @state.id)
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :warnings)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/application/_top_nav.html.erb
<%= link_to 'States', states_path%>
<%= link_to 'Cities', cities_path%>

app/views/cities/_form.html.erb
<%= form_with(model: [city], local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :state_id %>
    <%= form.select :state_id, options_for_select( State.all.collect { |u| [u.name, u.id] }, :selected => city.state_id ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'top_nav'%>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.state.name %></td>
        <td><%= link_to 'Show', city_path(city) %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city_path(city), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @city.state.name %>
</p>

<p>
  <strong>Forecasts:</strong>
  <%= link_to 'Forecasts',city_forecasts_path(@city, @forecasts) %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/forecasts/_form.html.erb
<%= form_with(model: [@city, forecast], local: true) do |form| %>
  <% if forecast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forecast.errors.count, "error") %> prohibited this forecast from being saved:</h2>

      <ul>
      <% forecast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :min_temp %>
    <%= form.number_field :min_temp %>
  </div>

  <div class="field">
    <%= form.label :max_temp %>
    <%= form.number_field :max_temp %>
  </div>

  <div class="field">
    <%= form.label :short_description %>
    <%= form.text_field :short_description %>
  </div>

  <div class="field">
    <%= form.label :chance_of_rain %>
    <%= form.number_field :chance_of_rain %>
  </div>

  <div class="field">
    <%= form.label :long_description %>
    <%= form.text_area :long_description %>
  </div>

  <div class="field">
    <%= form.label :uv_index %>
    <%= form.text_field :uv_index %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :possible_rainfall %>
    <%= form.text_field :possible_rainfall %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_area :image_url %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.select :city_id, options_for_select( City.all.collect { |u| [u.name, u.id] }, :selected => forecast.city_id ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forecasts/edit.html.erb
<h1>Editing Forecast</h1>

<%= render 'form', city: @city, forecast: @forecast %>

<%= link_to 'Show', city_forecast_path(@city, @forecast) %> |
<%= link_to 'Back', city_forecasts_path(@city) %>

app/views/forecasts/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'top_nav'%>

<h1>Forecasts</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Image url</th>
      <th>City</th>
      <th>Min temp</th>
      <th>Max temp</th>
      <th>Short description</th>
      <th>Chance of rain</th>
      <th>Long description</th>
      <th>Uv index</th>
      <th>Possible rainfall</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forecasts.each do |forecast| %>
      <tr>
        <td><%= forecast.date %></td>
        <td><%= image_tag(forecast.image_url) %></td>
        <td><%= forecast.city.name %></td>
        <td><%= forecast.min_temp %></td>
        <td><%= forecast.max_temp %></td>
        <td><%= forecast.short_description %></td>
        <td><%= forecast.chance_of_rain %>%</td>
        <td><%= forecast.long_description %></td>
        <td><%= forecast.uv_index %></td>
        <td><%= forecast.possible_rainfall %></td>
        <td><%= link_to 'Show', city_forecast_path(@city, forecast) %></td>
        <td><%= link_to 'Edit', edit_city_forecast_path(@city, forecast) %></td>
        <td><%= link_to 'Destroy', city_forecast_path(@city, forecast), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forecast', new_city_forecast_path %>

app/views/forecasts/new.html.erb
<h1>New Forecast</h1>

<%= render 'form', city: @city, forecast: @forecast %>

<%= link_to 'Back', city_forecasts_path(@city) %>

app/views/forecasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Min temp:</strong>
  <%= @forecast.min_temp %>
</p>

<p>
  <strong>Max temp:</strong>
  <%= @forecast.max_temp %>
</p>

<p>
  <strong>Short description:</strong>
  <%= @forecast.short_description %>
</p>

<p>
  <strong>Chance of rain:</strong>
  <%= @forecast.chance_of_rain %>
</p>

<p>
  <strong>Long description:</strong>
  <%= @forecast.long_description %>
</p>

<p>
  <strong>Uv index:</strong>
  <%= @forecast.uv_index %>
</p>

<p>
  <strong>Date:</strong>
  <%= @forecast.date %>
</p>

<p>
  <strong>Possible rainfall:</strong>
  <%= @forecast.possible_rainfall %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @forecast.image_url %>
</p>

<p>
  <strong>City:</strong>
  <%= @forecast.city.name %>
</p>

<%= link_to 'Edit', edit_city_forecast_path(@forecast, @city) %> |
<%= link_to 'Back', city_forecasts_path(@city) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecast</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/states/_form.html.erb
<%= form_with(model: state, local: true) do |form| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :warnings %>
    <%= form.text_area :warnings %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'top_nav'%>

<h1>States</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Warnings</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= state.warnings %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<p>
  <strong>Cities:</strong>
    <ul>
      <% @cities.each do |city| %>
        <li><%= link_to "#{city.name}", city_path(city) %>
      <% end %>
    </ul>
</p>

<p>
  <strong>Warnings:</strong>
  <%= @state.warnings %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>